### ISSUE TITLE
Suggested network configs for student model for knowledge distillation

### ISSUE THREAD

**Issue by mylifeasazucchini** [mmaaz60/EdgeNeXt#12]
Hi! thank you for sharing your amazing work!

 I have tried EdgeNext for Semantic segmentation and it works really well! However, I am targeting an even lighter model << 1 Million params, hence,  I have been trying Knowledge Distillation from a Larger EdgeNext model to a student network (which is basically a smaller EdgeNext model with number of channels halved) , however it seems that I was a bit too aggressive with dropping channels and performance is hard stuck at around 0.3 mIoU while the teacher EdgeNext_XXS was able to reach as high as 0.93 mIoU on the same dataset. Would you have any suggestions about how to create the student EdgeNext model ? 

Any help will be super appreciated! :)

**Comment by mmaaz60** [comment]
Hi @mylifeasazucchini,

Thank you for your interest in our work. It is good to hear that you were able to achieve good segmentation results using EdgeNeXt. For creating tiny student model, I would suggest you follow the uniform scaling of width, depth and resolution of the network. For example, you may try depths of [2, 2, 6, 2] or even [1, 1, 3, 1] and accordingly adjust the channels. You may increase the input resolution by a margin as well.

Also, did you try using [`EdgeNeXt-XXS`](https://github.com/mmaaz60/EdgeNeXt/blob/52d331e37c61d04f5acbe85a00e817cf8d22cc6f/models/model.py#L14) as student model? It has only 1.3M parameters.

I hope it will help. Please let me know if you will have any questions. Thanks

**Comment by mylifeasazucchini** [comment]
Thanks for the quick response! I actually started out with the EdgeNext-XXS model :) but when deploying our model to app, the loading time for the model was still a bit large, leading to app being unresponsive/crashing at times, plus the segmentation task for my model is quite easy in my opinion and I feel like an even lighter version of EdgeNext could do the job!  

BTW as a closing comment, when you say "You may increase the input resolution by a margin as well" did you mean the input image size to the segmentation model( basically EdgeNext) or did I misunderstand something ?

Also, here is my current config, I will update this issue later depending on my training progress :
_depths=(2, 2, 6, 2), dims=(20, 36, 64, 124), heads=(4, 4, 4, 4)_

Thanks again!

**Comment by mmaaz60** [comment]
Hi @mylifeasazucchini, How is it going with the nano EdgeNeXt training?

> BTW as a closing comment, when you say "You may increase the input resolution by a margin as well" did you mean the input image size to the segmentation model( basically EdgeNext) or did I misunderstand something ?

Yes, you understood it correctly.

> Also, here is my current config, I will update this issue later depending on my training progress : _depths=(2, 2, 6, 2), dims=(20, 36, 64, 124), heads=(4, 4, 4, 4)_

The no. of channels look reasonable. Maybe we can try reducing the number of heads as well.

**Comment by mylifeasazucchini** [comment]
Heyy!

Thanks for the clarification! I tried the discussed nano-EdgeNeXt but I think there were a couple of things lacking in my implementation as the mIoU stayed hard stuck at 0.4 mIoU :( But I think I know the reasons behind those and here are some key points (it is a bit long but I thought it will be interesting for you! )

1. I had this assumption that for Knowledge Distillation I wouldn't need to pretrain the nano-EdgeNeXt on ImageNet or some other diverse dataset and I could directly distill from the larger trained model but this is wrong and closer look at some papers and some discussions with other authors (ex: https://github.com/winycg/CIRKD/issues/9) they all suggest some level of pre-training the backbone and then training that model the best that one can for my specific segmentation tasks and only then trying KD .

2. But since I work in an organization, using datasets like ImageNet = License issues later on so I have been looking at some unsupervised "pre-tasks" that would force the network to learn something about the features in my dataset (ex: https://github.com/akwasigroch/Pretext-Invariant-Representations) 

3. So the current training pipeline is a 3 stage work: **Stage 1**: Unsupervised Pre-task, then **Stage 2**: Training the nano EdgeNeXt using weights from Stage 1 for semantic segmentation and finally **Stage 3**: KD

But yeah this work will take some time as I also have other projects parallelly! So I promise to update this issue when I have something interesting but maybe we could close this issue with a closing comment from you about what I just said :')

**Comment by mmaaz60** [comment]
Hi @mylifeasazucchini,

Do you have any update on your project? Thanks
