### ISSUE TITLE
Is there any way to finetune EdgeNeXt_xx_small?

### ISSUE THREAD

**Issue by dlarhkd1211** [mmaaz60/EdgeNeXt#13]
Hi
I want to finetune EdgeNeXt_xx_small with my custom dataset.(class = 3)
When i using 'resume' argument, it makes error of size mismatch for head.weight and head.bias
![image](https://user-images.githubusercontent.com/54428934/191406910-c6b4cd43-b2e6-47f7-b46e-d49218320366.png)

How can i finetune [EdgeNeXt_xx_small](https://github.com/apple/ml-cvnets/blob/main/docs/source/en/general/README-model-zoo.md#mobilevitv2-256x256) with my custom data?

Thanks :)

**Comment by mmaaz60** [comment]
Hi @dlarhkd1211,

I have added the support to fine-tune EdgeNeXt model on custom image-classification dataset. Please pass the following extra arguments to `main.py` for fine-tuning,

`--finetune <pretrained weights path> --nb_classes <no. of classes for fine-tuning> --data_set image_folder --data_path <path to training dataset> --eval_data_path <path to val dataset>`

I hope this will help, do let me know if you face any difficulty. Thanks

**Comment by dlarhkd1211** [comment]
> Hi @dlarhkd1211,
> 
> I have added the support to fine-tune EdgeNeXt model on custom image-classification dataset. Please pass the following extra arguments to `main.py` for fine-tuning,
> 
> `--finetune <pretrained weights path> --nb_classes <no. of classes for fine-tuning> --data_set image_folder --data_path <path to training dataset> --eval_data_path <path to val dataset>`
> 
> I hope this will help, do let me know if you face any difficulty. Thanks

It works well. Thanks for your help
