### ISSUE TITLE
classification

### ISSUE THREAD

**Issue by smallYangRun** [mmaaz60/EdgeNeXt#14]
I would like to try training edgenext_xx.
Can you tell me the parameter settings?
And can i see your train log?

**Comment by mmaaz60** [comment]
Hi @yoouaicv,

The following command can be used to reproduce our results for `xx` model. Note that we do not use Auto Augmentation while training extra-extra small model as we found that this model is not prune to overfitting.

```
python -m torch.distributed.launch --nproc_per_node=8 main.py \
--model edgenext_xx_small --drop_path 0.0  --aa "" \
--batch_size 256 --lr 6e-3 --update_freq 2 \
--model_ema true --model_ema_eval true \
--data_path </path/to/imagenet-1k> \
--output_dir </path/to/save_results> \
--use_amp True --multi_scale_sampler
```

Unfortunately, I was not able to find the training logs, I will upload it here if found. Thanks

**Comment by yoouaicv** [comment]
Thanks for your reply. I'm trying to train a new idea, and i don't know if anyone has realized it, so I'd like your help to review it and tell me.
