### ISSUE TITLE
Convert model to libtorch.

### ISSUE THREAD

**Issue by GGongSoWon** [mmaaz60/EdgeNeXt#16]
Hello!
I would like to use the edgenext model in libtorch.
There are errors that appear when you use two methods to convert to a .pt file:

**1. Create a .pt file with torch.jit.trace (model, input) and run it with libtorch**

- Debug mode : "abort() has been called" error occurred

- Release mode : The output value is different from the original model.

  - python original output shape : (1, 7)

  - C++ libtorch output shape : (1, 2)

**2. When creating a .pt file with torch.jit.script(model) in python**
##################################################
forward(__torch__.torch.nn.modules.conv.___torch_mangle_253.Conv2d self, Tensor input) -> (Tensor):
Expected a value of type 'Tensor' for argument 'input' but instead found type 'Optional[Tensor]'.
##################################################
Error Occurred

**Comment by yash-khurana** [comment]
Have you tried converting it to other formats, such as openvino or trt?
