### ISSUE TITLE
About ablation 

### ISSUE THREAD

**Issue by wsy-yjys** [mmaaz60/EdgeNeXt#19]
> Table 7. Ablation on different components of EdgeNeXt and SDTA encoder. The results show the benefits of SDTA encoders and adaptive kernels in our design. Further, adaptive branching and positional encoding (PE) are also required in SDTA module.
> 
> ![image](https://user-images.githubusercontent.com/78601159/226109852-30933588-6c5c-4950-a2e5-5854b083a5a0.png)

In the table 7. I'm curious why the delay is the same with the base model when there is no adaptive branching? Looking forward to your reply~

**Comment by mmaaz60** [comment]
Hi @wsy-yjys,

Thank You for your interest in our work. The inference time you are referring to is measured on a local server with NVIDIA A100 GPU & Intel(R) Xeon(R) Gold 5317 CPU @ 3.00GHz using PyTorch. In this setting the major bottleneck is the channel attention in SDTA module. Also, in `w/o Adaptive Branching` we replace the adaptive branching component with standard depth wise convolution of corresponding size. All this might be the reason of nearly equal inference time in both cases. Please let me know if you have any questions or have any additional comments/insights.

**Best Regards,**
Muhammad Maaz

**Comment by wsy-yjys** [comment]
tkank you for your reply！I got  it.
