### ISSUE TITLE
What the year of datasets of ImageNet-1K to use?

### ISSUE THREAD

**Issue by xjohnxjohn** [mmaaz60/EdgeNeXt#4]
Hi,
 Great works. What the datasets of ImageNet-1K to use. It have many 
ILSVRC 2017
ILSVRC 2016
ILSVRC 2015
ILSVRC 2014
ILSVRC 2013
ILSVRC 2012
ILSVRC 2011
ILSVRC 2010

**Comment by mmaaz60** [comment]
Hi @xjohnxjohn,

It is ILSVRC 2017 if I remember correctly and can be downloaded from [kaggle](https://www.kaggle.com/competitions/imagenet-object-localization-challenge/data). Do let me know if you face any difficulty. Good Luck!

**Comment by mmaaz60** [comment]
Feel free to reopen if you have any further questions about the dataset.
