### ISSUE TITLE
EdgeNeXt for semantic segmentation

### ISSUE THREAD

**Issue by lkdci** [mmaaz60/EdgeNeXt#5]
Hi, Thanks for your work.
Is there any plan to share your implementation for semantic segmentation with PascalVOC dataset? Perhaps instructions on how to build the modules or pth checkpoints / onnx models?

**Comment by mmaaz60** [comment]
Hi @lkdci,

Thank you for your interest in our work. We do have plans to release segmentation codes and models, however it may take some time. Some extra details; we implemented our EdgeNeXt model in [MobileViT](https://github.com/apple/ml-cvnets) for segmentation experiments. I am attaching the `.pt` checkpoints here in case it might be helpful for now.
[EdgeNeXt_DeepLabV3.zip](https://github.com/mmaaz60/EdgeNeXt/files/9046051/EdgeNeXt_DeepLabV3.zip)

Thanks

**Comment by lkdci** [comment]
Hi @mmaaz60, thanks for the fast reply. So basically the backbone remains the same, and an ASPP module is used as Decoder?

**Comment by mmaaz60** [comment]
> Hi @mmaaz60, thanks for the fast reply. So basically the backbone remains the same, and an ASPP module is used as Decoder?

Hi @lkdci, yes you are right. Thanks

**Comment by AndPuQing** [comment]
@mmaaz60 Hi, Can give more details? I am trying to use edgenext for semantic segmentation of bdd100k, but after training 160k, the effect is not satisfactory, do you use any auxiliary head?

**Comment by mmaaz60** [comment]
Hi @AndPuQing,

Apologies for the late reply. We do not use any auxiliary head. Did you try tuning your learning rate?
