### ISSUE TITLE
Reproduced 79.1 for edgenext_small, a random error?

### ISSUE THREAD

**Issue by zhangzjn** [mmaaz60/EdgeNeXt#8]
I retrain the edgenext_small using the official code and coomand with 8*V100, but a get 79.1 that has a minor gap with the paper's result 79.4. Is this gap a random error or something maybe left out? Thanks for the great work

**Comment by mmaaz60** [comment]
> I retrain the edgenext_small using the official code and coomand with 8*V100, but a get 79.1 that has a minor gap with the paper's result 79.4. Is this gap a random error or something maybe left out? Thanks for the great work

Hi @zhangzjn,

Thank you for using EdgeNeXt. In my opinion its normal as ImageNet-1K training from scratch do have similar standard deviation. Further, please verify if you are using the same hyperparameter setting as mentioned under implementation details in our [paper](https://arxiv.org/pdf/2206.10589.pdf). To be clear on the point, we trained our models on 8*A100 GPUs using PyTorch automatic mixed precision (AMP). Please let me know if you have any questions.
